source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.0.1'
gem 'sqlite3'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

# Added

## Devise
### Flexible authentication solution for Rails with Warden
gem 'devise', '~> 4.2'
## /Devise

## Bootstrap
### The most popular HTML, CSS, and JavaScript framework for developing responsive,
### mobile first projects on the web. http://getbootstrap.com
gem 'bootstrap', '~> 4.0.0.alpha6'
## /Bootstrap

## Glyphicons
gem 'bootstrap-glyphicons'
## /Glyphicons

## Acts as Votable
### Rails gem to allowing records to be votable
gem 'acts_as_votable', '~> 0.10.0'
## /Acts as Votable

## Simple Form
gem 'simple_form', '~> 3.4'
gem 'record_tag_helper', '~> 1.0'
## /Simple Form


# /Added

group :development, :test do
  gem 'byebug', platform: :mri
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
