# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b0d06e650a5018c0ce29a62dda24f0ab876a3060e3f1225757226b2ba2b94e101201706c2de6481210ebb2816f17feb7be16e310558ae032d38e3bede395d87

test:
  secret_key_base: 6c756e7c3dd7a0aa466136ece53a5c69f876f13664d58114d90fa3d8736d17904f607c64439f3d5d620764c11897a83b64f6e73ff906d6cc9ef7d371b2cdc2e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
