# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46f469a2c47d71455d9e77f969f1dcc259677a6e816758baca649c9757f9f5c4e2ea621835e7ddb62550ac1cd3093566951f141b3610f41c03b26d33c894d717

test:
  secret_key_base: 5bf3f589f27e6e8c963e8f5e63f06546d8f80b8a7a9f1bb155005772cbe7903ee2a03a3fdeb9dfcb8ef7cba255201550701d5753e5625d8c29214823f18091f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
