source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.0.2'
gem 'sqlite3'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

# Added

## Devise Gem
### Flexible authentication solution for Rails with Warden
gem 'devise', '~> 4.2', '>= 4.2.1'
## /Devise Gem

## Paperclip Gem
### thoughtbot Easy upload management for ActiveRecord
gem 'paperclip', '~> 5.1'
## /Paperclip Gem

## Bootstrap Gem
### The most popular HTML, CSS, and JavaScript framework for developing
### responsive, mobile first projects on the web.
gem 'bootstrap', '~> 4.0.0.alpha6'
## /Bootstrap Gem


# /Added

group :development, :test do
  gem 'byebug', platform: :mri
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
