source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.0.1'
gem 'sqlite3'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

## Added

### Devise Gem
### Flexible authentication solution for Rails with Warden
gem 'devise', '~> 4.2'

### Active-Admin Gem
### The administration framework for Ruby on Rails.
gem 'activeadmin', git: 'https://github.com/activeadmin/activeadmin'
### Using activeadmin 1.0.0.pre4
gem 'inherited_resources', git: 'https://github.com/activeadmin/inherited_resources'
### Using inherited_resources 1.7.0

### Skins for active admin.
gem 'active_skin'

### Paper Clip Gem
### Easy upload management for ActiveRecord
gem "paperclip", "~> 5.0.0"

group :development, :test do
  gem 'byebug', platform: :mri
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
