source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end
gem 'rails', '~> 5.0.2'
gem 'sqlite3'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

# Haml
## Haml (HTML Abstraction Markup Language) is a layer on top of HTML or XML that's designed
## to express the structure of documents in a non-repetitive, elegant, and easy way by using
## indentation rather than closing tags and allowing Ruby to be embedded with ease.
## It was originally envisioned as a plugin for Ruby on Rails, but it can function as a
## stand-alone templating engine.
gem 'haml', '~> 4.0', '>= 4.0.7'
# /Haml

# Simple_form
## Forms made easy!
gem 'simple_form', '~> 3.4'
# /Simple_form

# Bootstrap
gem 'bootstrap', '~> 4.0.0.alpha6'
# /Bootstrap

# Paperclip
## Easy upload management for ActiveRecord
gem "paperclip", "~> 5.0.0"
# /Paperclip

# Cocoon
## Unobtrusive nested forms handling, using jQuery. Use this and discover cocoon-heaven.
gem 'cocoon', '~> 1.2', '>= 1.2.9'
# /Cocoon

# Devise
gem 'devise', '~> 4.2'
## Flexible authentication solution for Rails with Warden
# /Devise

group :development, :test do
  gem 'byebug', platform: :mri
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
