# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 492fb4f3d390efa63edbce2471d4bb95216d2e25ca143b9787bf5de1b5505f5f21255fe9dfaf6ec76ecf758dec6630973c303f8642a57fc6a55e5a1d8eab769e

test:
  secret_key_base: 1b173f350726c62b744c49a5a4d742479ddf39d4844dec0aa93bdf688242873fb6c38c7635168085c49d6e849763209c26b029d1a9299520abbfd3836ea0fa3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
