# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95304efc1641711ed066d62b7ce655ab7cb0a4f7c7d4b06392e73a84cd624ef5974b065d7867f809ca36517708c8ecbb7a396538ff9941dbd4b667fbffbad1b6

test:
  secret_key_base: 3976e3b44c8bdfb516ba39b057023f6cc9da8415ed51cad3752cd26273ca65a0c9e9a660453016734b642ff9c67336afee2d282186a134ad7597d18d0ca13f69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
