# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37c024fb2e31e18838b2ebe3462de0e4c55454bd72c1cd6a24ba08e0155cea3647db7cde3f6e80da9e842eebce594e77306e8905cc0c9718133df7588616ea18

test:
  secret_key_base: bb63b3d2eb5b15062378feccbb9f1890cb6d1b5c4fc904dbdc6e66c39cf6895593b833f42432abf7ae3b1f0215e226482885b0ff036a78c52b039301a16c09f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
